#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:nil d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t
#+OPTIONS: num:t p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t timestamp:t
#+OPTIONS: title:t toc:t todo:t |:t
#+TITLES: future
#+DATE: <2017-09-12 Tue>
#+AUTHORS: weiwu
#+EMAIL: victor.wuv@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.4)


* future trade simulation
** functions
- 合成一个连续合约.
- future calendar spread.
- rolling on constant maturity.
- buy current and roll.
- buy constant maturity trend following.
** futures:
由期货交易所统一制定的、规定在将来某一特定的时间和地点交割一定数量和质量标的物的标准化合约。

*** 期货合约命名规则：
品种名+交割月份

*** 期货合约品种:
商品期货和金融期货。

商品期货又分工业品（可细分为金属商品（贵金属与非贵金属商品）、能源商品）、农产品、其他商品等。

金融期货主要是传统的金融商品（工具）如股指、利率、汇率等，各类期货交易包括期权交易等。

**** 商品期货

农产品期货：如大豆、豆油、豆粕、籼稻、小麦、玉米、棉花、白糖、咖啡、猪腩、菜籽油、棕榈油。

金属期货：如铜、铝、锡、铅、锌、镍、黄金、白银、螺纹钢、线材。

能源期货：如原油（塑料、PTA、PVC）、汽油（甲醇）、燃料油。新兴品种包括气温、二氧化碳排放配额、天然橡胶。

**** 金融期货

股指期货：如英国FTSE指数、德国DAX指数、东京日经平均指数、香港恒生指数、沪深300指数

利率期货（Interest rate futures）：利率期货是指以债券类证券为标的物的期货合约，它可以避免利率波动所引起的证券价格变动的风险。利率期货一般可分为短期利率期货和长期利率期货，前者大多以银行同业拆借中场3月期利率为标的物、后者大多以5年期以上长期债券为标的物。

外汇期货(foreign exchange futures)又称为货币期货，是一种在最终交易日按照当时的汇率将一种货币兑换成另外一种货币的期货合约。是指以汇率为标的物的期货合约，用来回避汇率风险。它是金融期货中最早出现的品种。

贵金属期货

主要以黄金、白银为标的物的期货合约。

例如沪深300股指期货为’IF’, 贵金属按化学元素周期表命名，黄金为‘au’，白银为‘ag’。

*** 国内future exchange:
**** 郑州商品交易所（ZCE）
交易的品种有强筋小麦、普通小麦、PTA、一号棉花、白糖、菜籽油、早籼稻、玻璃、菜籽、菜粕、甲醇等16个期货品种.

**** 上海期货交易所（SHFE）
目前上市交易的有黄金、白银、铜、铝、锌、铅、螺纹钢、线材、燃料油、天然橡胶沥青等11个期货品种。

**** 大连商品交易所（DCE）
是中国东北地区唯一一家期货交易所。上市交易的有玉米、黄大豆1号、黄大豆2号、豆粕、豆油、棕榈油、聚丙烯、聚氯乙烯、塑料、焦炭、焦煤、铁矿石、胶合板、纤维板、鸡蛋等15个期货品种。

**** 中国金融期货交易所（CFFEX）
交易品种有股指期货，国债期货。

*** dominant_future - 期货主力合约
合约首次上市时，以当日收盘同品种持仓量最大者作为从第二个交易日开始的主力合约。当同品种其他合约持仓量在收盘后超过当前主力合约1.1倍时，从第二个交易日开始进行主力合约的切换。日内不会进行主力合约的切换。

*** 保证金
参考各交易所各品种手册。

for example:
| 交易品种 | 黄金 |
| 交易单位 | 1000克/手 |
| 报价单位 | 元（人民币）/克 |
| 最小变动价位 | 0.05元/克 |
| 每日价格最大波动限制 | 不超过上一交易日结算价±3% |
| 合约交割月份 | 最近三个连续月份的合约以及最近13个月以内的双月合约 |
| 交易时间 | 上午9:00－11:30 ，下午1:30－3:00和交易所规定的其他交易时间 |
| 最后交易日 | 合约交割月份的15日（遇法定假日顺延） |
| 交割日期 | 最后交易日后连续五个工作日 |
| 交割品级 | 金含量不小于99.95%的国产金锭及经交易所认可的伦敦金银市场协会（LBMA）认定的合格供货商或精炼厂生产的标准金锭  |
| 交割地点 | 交易所指定交割金库
| 最低交易保证金 | 合约价值的4% |
| 交割方式 | 实物交割 |
| 交易代码 | AU |
| 上市交易所 | 上海期货交易所 |
** 算法
仓位金：总资金*（X%-Y%）；

单笔最大允许亏损额<=总资产*Z%；

单手开仓价：（现价*交易单位*保证金）+手续费；

默认手数（最大开仓）：仓位金/单手开仓价；

每笔最大止损点数：最大允许亏损额/开仓手数/交易单位/最小变动价位；

期货品种波动一个价位的值：最小变动价*交易单位*开仓手数；
