# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metaInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='metaInfo.proto',
  package='com.gftchina.common.calcProtocol',
  serialized_pb=_b('\n\x0emetaInfo.proto\x12 com.gftchina.common.calcProtocol\"_\n\x0cobserverInfo\x12<\n\x04type\x18\x01 \x02(\x0e\x32..com.gftchina.common.calcProtocol.observerType\x12\x11\n\tlookAhead\x18\x02 \x02(\x02\"\xfe\x01\n\x07\x63olMeta\x12\x12\n\ncolumnName\x18\x01 \x02(\t\x12\x0f\n\x07\x63olType\x18\x02 \x02(\x05\x12\x10\n\x08gidOsets\x18\x03 \x03(\t\x12\x10\n\x08timezone\x18\x04 \x01(\x05\x12\x16\n\x0eperiodInterval\x18\x05 \x01(\x02\x12\x41\n\tobservers\x18\x06 \x03(\x0b\x32..com.gftchina.common.calcProtocol.observerInfo\x12\x15\n\rdecimalDigits\x18\x07 \x01(\x05\x12\x14\n\x0cphysicalUnit\x18\x08 \x01(\t\x12\x10\n\x08\x64\x61taZoom\x18\t \x01(\x05\x12\x10\n\x08\x64ispUnit\x18\n \x01(\x05\"l\n\x08\x63\x61lendar\x12\x16\n\x0eregularDaysGid\x18\x01 \x01(\t\x12\x13\n\x0bindexPickle\x18\x02 \x01(\x0c\x12\x0c\n\x04jGid\x18\x03 \x01(\t\x12\x13\n\x0btColumnName\x18\x04 \x01(\t\x12\x10\n\x08\x61vgDelta\x18\x05 \x01(\x02\"\xc3\x01\n\ttableMeta\x12\x10\n\x08primaryT\x18\x01 \x01(\t\x12\x37\n\x04\x63ols\x18\x02 \x03(\x0b\x32).com.gftchina.common.calcProtocol.colMeta\x12\r\n\x05max_t\x18\x03 \x01(\x03\x12\r\n\x05min_t\x18\x04 \x01(\x03\x12\r\n\x05index\x18\x05 \x01(\x0c\x12>\n\nptCalendar\x18\x06 \x01(\x0b\x32*.com.gftchina.common.calcProtocol.calendar\"]\n\x0clookbackStep\x12\x37\n\x03\x63\x61l\x18\x01 \x02(\x0b\x32*.com.gftchina.common.calcProtocol.calendar\x12\x14\n\x0clookbackStep\x18\x02 \x02(\x05\"S\n\x08jAndMeta\x12\x0c\n\x04jGid\x18\x01 \x02(\t\x12\x39\n\x04meta\x18\x02 \x02(\x0b\x32+.com.gftchina.common.calcProtocol.tableMeta\"I\n\tjMetaPack\x12<\n\x08\x61llMetas\x18\x01 \x03(\x0b\x32*.com.gftchina.common.calcProtocol.jAndMeta*8\n\x0cobserverType\x12\x0b\n\x07INSIDER\x10\x01\x12\x0f\n\x0b\x44\x41TA_VENDOR\x10\x02\x12\n\n\x06PUBLIC\x10\x03')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_OBSERVERTYPE = _descriptor.EnumDescriptor(
  name='observerType',
  full_name='com.gftchina.common.calcProtocol.observerType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INSIDER', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DATA_VENDOR', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PUBLIC', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=969,
  serialized_end=1025,
)
_sym_db.RegisterEnumDescriptor(_OBSERVERTYPE)

observerType = enum_type_wrapper.EnumTypeWrapper(_OBSERVERTYPE)
INSIDER = 1
DATA_VENDOR = 2
PUBLIC = 3



_OBSERVERINFO = _descriptor.Descriptor(
  name='observerInfo',
  full_name='com.gftchina.common.calcProtocol.observerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='com.gftchina.common.calcProtocol.observerInfo.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lookAhead', full_name='com.gftchina.common.calcProtocol.observerInfo.lookAhead', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=147,
)


_COLMETA = _descriptor.Descriptor(
  name='colMeta',
  full_name='com.gftchina.common.calcProtocol.colMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='columnName', full_name='com.gftchina.common.calcProtocol.colMeta.columnName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='colType', full_name='com.gftchina.common.calcProtocol.colMeta.colType', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gidOsets', full_name='com.gftchina.common.calcProtocol.colMeta.gidOsets', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timezone', full_name='com.gftchina.common.calcProtocol.colMeta.timezone', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='periodInterval', full_name='com.gftchina.common.calcProtocol.colMeta.periodInterval', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='observers', full_name='com.gftchina.common.calcProtocol.colMeta.observers', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='decimalDigits', full_name='com.gftchina.common.calcProtocol.colMeta.decimalDigits', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='physicalUnit', full_name='com.gftchina.common.calcProtocol.colMeta.physicalUnit', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dataZoom', full_name='com.gftchina.common.calcProtocol.colMeta.dataZoom', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dispUnit', full_name='com.gftchina.common.calcProtocol.colMeta.dispUnit', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=404,
)


_CALENDAR = _descriptor.Descriptor(
  name='calendar',
  full_name='com.gftchina.common.calcProtocol.calendar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='regularDaysGid', full_name='com.gftchina.common.calcProtocol.calendar.regularDaysGid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='indexPickle', full_name='com.gftchina.common.calcProtocol.calendar.indexPickle', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jGid', full_name='com.gftchina.common.calcProtocol.calendar.jGid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tColumnName', full_name='com.gftchina.common.calcProtocol.calendar.tColumnName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='avgDelta', full_name='com.gftchina.common.calcProtocol.calendar.avgDelta', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=514,
)


_TABLEMETA = _descriptor.Descriptor(
  name='tableMeta',
  full_name='com.gftchina.common.calcProtocol.tableMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='primaryT', full_name='com.gftchina.common.calcProtocol.tableMeta.primaryT', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cols', full_name='com.gftchina.common.calcProtocol.tableMeta.cols', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_t', full_name='com.gftchina.common.calcProtocol.tableMeta.max_t', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='min_t', full_name='com.gftchina.common.calcProtocol.tableMeta.min_t', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='index', full_name='com.gftchina.common.calcProtocol.tableMeta.index', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ptCalendar', full_name='com.gftchina.common.calcProtocol.tableMeta.ptCalendar', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=712,
)


_LOOKBACKSTEP = _descriptor.Descriptor(
  name='lookbackStep',
  full_name='com.gftchina.common.calcProtocol.lookbackStep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cal', full_name='com.gftchina.common.calcProtocol.lookbackStep.cal', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lookbackStep', full_name='com.gftchina.common.calcProtocol.lookbackStep.lookbackStep', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=714,
  serialized_end=807,
)


_JANDMETA = _descriptor.Descriptor(
  name='jAndMeta',
  full_name='com.gftchina.common.calcProtocol.jAndMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jGid', full_name='com.gftchina.common.calcProtocol.jAndMeta.jGid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='meta', full_name='com.gftchina.common.calcProtocol.jAndMeta.meta', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=809,
  serialized_end=892,
)


_JMETAPACK = _descriptor.Descriptor(
  name='jMetaPack',
  full_name='com.gftchina.common.calcProtocol.jMetaPack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='allMetas', full_name='com.gftchina.common.calcProtocol.jMetaPack.allMetas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=894,
  serialized_end=967,
)

_OBSERVERINFO.fields_by_name['type'].enum_type = _OBSERVERTYPE
_COLMETA.fields_by_name['observers'].message_type = _OBSERVERINFO
_TABLEMETA.fields_by_name['cols'].message_type = _COLMETA
_TABLEMETA.fields_by_name['ptCalendar'].message_type = _CALENDAR
_LOOKBACKSTEP.fields_by_name['cal'].message_type = _CALENDAR
_JANDMETA.fields_by_name['meta'].message_type = _TABLEMETA
_JMETAPACK.fields_by_name['allMetas'].message_type = _JANDMETA
DESCRIPTOR.message_types_by_name['observerInfo'] = _OBSERVERINFO
DESCRIPTOR.message_types_by_name['colMeta'] = _COLMETA
DESCRIPTOR.message_types_by_name['calendar'] = _CALENDAR
DESCRIPTOR.message_types_by_name['tableMeta'] = _TABLEMETA
DESCRIPTOR.message_types_by_name['lookbackStep'] = _LOOKBACKSTEP
DESCRIPTOR.message_types_by_name['jAndMeta'] = _JANDMETA
DESCRIPTOR.message_types_by_name['jMetaPack'] = _JMETAPACK
DESCRIPTOR.enum_types_by_name['observerType'] = _OBSERVERTYPE

observerInfo = _reflection.GeneratedProtocolMessageType('observerInfo', (_message.Message,), dict(
  DESCRIPTOR = _OBSERVERINFO,
  __module__ = 'metaInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.observerInfo)
  ))
_sym_db.RegisterMessage(observerInfo)

colMeta = _reflection.GeneratedProtocolMessageType('colMeta', (_message.Message,), dict(
  DESCRIPTOR = _COLMETA,
  __module__ = 'metaInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.colMeta)
  ))
_sym_db.RegisterMessage(colMeta)

calendar = _reflection.GeneratedProtocolMessageType('calendar', (_message.Message,), dict(
  DESCRIPTOR = _CALENDAR,
  __module__ = 'metaInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.calendar)
  ))
_sym_db.RegisterMessage(calendar)

tableMeta = _reflection.GeneratedProtocolMessageType('tableMeta', (_message.Message,), dict(
  DESCRIPTOR = _TABLEMETA,
  __module__ = 'metaInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.tableMeta)
  ))
_sym_db.RegisterMessage(tableMeta)

lookbackStep = _reflection.GeneratedProtocolMessageType('lookbackStep', (_message.Message,), dict(
  DESCRIPTOR = _LOOKBACKSTEP,
  __module__ = 'metaInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.lookbackStep)
  ))
_sym_db.RegisterMessage(lookbackStep)

jAndMeta = _reflection.GeneratedProtocolMessageType('jAndMeta', (_message.Message,), dict(
  DESCRIPTOR = _JANDMETA,
  __module__ = 'metaInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.jAndMeta)
  ))
_sym_db.RegisterMessage(jAndMeta)

jMetaPack = _reflection.GeneratedProtocolMessageType('jMetaPack', (_message.Message,), dict(
  DESCRIPTOR = _JMETAPACK,
  __module__ = 'metaInfo_pb2'
  # @@protoc_insertion_point(class_scope:com.gftchina.common.calcProtocol.jMetaPack)
  ))
_sym_db.RegisterMessage(jMetaPack)


# @@protoc_insertion_point(module_scope)
